/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dealership;

import java.io.File;
import javax.swing.*;
import java.io.FileNotFoundException; 
import java.io.FileWriter; 
import java.io.IOException; 
import java.io.PrintWriter;

/**
 *
 * @author nellt
 */
public class Finance extends javax.swing.JFrame {

    /**
     * Creates new form Finance
     */
    public Finance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Personal_Label = new javax.swing.JLabel();
        FirstName_Label = new javax.swing.JLabel();
        FirstName_TextField = new javax.swing.JTextField();
        Surname_Label = new javax.swing.JLabel();
        Surname_TextField = new javax.swing.JTextField();
        CellNo_Label = new javax.swing.JLabel();
        Cell_TextField = new javax.swing.JTextField();
        IDNo_Label = new javax.swing.JLabel();
        ID_TextField = new javax.swing.JTextField();
        Gender_Label = new javax.swing.JLabel();
        Gender_ComboBox = new javax.swing.JComboBox<>();
        Occupation_Label = new javax.swing.JLabel();
        Occupation_TextField = new javax.swing.JTextField();
        HomeAddress_TextField = new javax.swing.JTextField();
        HomeAddress_Label = new javax.swing.JLabel();
        WorkAdress_Label = new javax.swing.JLabel();
        WorkAddress_TextField = new javax.swing.JTextField();
        GrossPay_TextField = new javax.swing.JTextField();
        Gross_Label = new javax.swing.JLabel();
        NetPay_TextField = new javax.swing.JTextField();
        Net_Label = new javax.swing.JLabel();
        VaildLicense_Label = new javax.swing.JLabel();
        Yes_RadioButton = new javax.swing.JRadioButton();
        No_RadioButton = new javax.swing.JRadioButton();
        Vehicle_Label = new javax.swing.JLabel();
        Vehicle_ComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        Attachements = new javax.swing.JLabel();
        ID_Label = new javax.swing.JLabel();
        IDDoc_TextField = new javax.swing.JTextField();
        Browse1_Button = new javax.swing.JButton();
        PaySlip_Label = new javax.swing.JLabel();
        LastPayCheck_TextField = new javax.swing.JTextField();
        Browse2_Button = new javax.swing.JButton();
        Licence_Label = new javax.swing.JLabel();
        Licenses_TextField = new javax.swing.JTextField();
        Browse3_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Next_Label = new javax.swing.JLabel();
        FirstName2_Label = new javax.swing.JLabel();
        Cell2_TextField = new javax.swing.JTextField();
        CellNo2_Label = new javax.swing.JLabel();
        Next_Surname_TextField = new javax.swing.JTextField();
        Next_FirstName_TextField = new javax.swing.JTextField();
        Relationship_TextField = new javax.swing.JTextField();
        Surname2_Label = new javax.swing.JLabel();
        Relationship_Label = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        Submit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Personal_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Personal_Label.setText("Personal Information");

        FirstName_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstName_Label.setText("First Name");

        Surname_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Surname_Label.setText("Surname");

        CellNo_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CellNo_Label.setText("Cell No");

        IDNo_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDNo_Label.setText("ID No");

        Gender_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Gender_Label.setText("Gender");

        Gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non-binary", "Gender-fluid", "Agender", "Prefer not to respond", "Other" }));
        Gender_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gender_ComboBoxActionPerformed(evt);
            }
        });

        Occupation_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Occupation_Label.setText("Occupation");

        HomeAddress_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HomeAddress_Label.setText("Home Address");

        WorkAdress_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WorkAdress_Label.setText("Work Address");

        Gross_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Gross_Label.setText("Gross Pay");

        Net_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Net_Label.setText("Net Pay");

        VaildLicense_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VaildLicense_Label.setText("Vaild License");

        Yes_RadioButton.setText("Yes");

        No_RadioButton.setText("No");

        Vehicle_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Vehicle_Label.setText("Vehicle");

        Vehicle_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polo", "Polo Vivo", "T-Cross", "T-Roc" }));
        Vehicle_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vehicle_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Personal_Label)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstName_Label)
                                    .addComponent(Surname_Label)
                                    .addComponent(CellNo_Label))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cell_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Surname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IDNo_Label)
                                    .addComponent(Gender_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(HomeAddress_Label)
                                .addGap(18, 18, 18)
                                .addComponent(HomeAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(Gross_Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GrossPay_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(WorkAdress_Label)
                                    .addGap(18, 18, 18)
                                    .addComponent(WorkAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Net_Label)
                                        .addComponent(VaildLicense_Label)
                                        .addComponent(Vehicle_Label))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Vehicle_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(Yes_RadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(No_RadioButton))
                                        .addComponent(NetPay_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Occupation_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Occupation_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Personal_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HomeAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HomeAddress_Label))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FirstName_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(WorkAddress_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WorkAdress_Label))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Surname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Surname_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GrossPay_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Gross_Label))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cell_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CellNo_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NetPay_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Net_Label))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDNo_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender_Label)
                    .addComponent(Gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VaildLicense_Label)
                    .addComponent(Yes_RadioButton)
                    .addComponent(No_RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Vehicle_Label)
                        .addComponent(Vehicle_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Occupation_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Occupation_Label)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(573, 79));

        Attachements.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Attachements.setText("Attachements");

        ID_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ID_Label.setText("ID");

        Browse1_Button.setText("Browse");
        Browse1_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse1_ButtonActionPerformed(evt);
            }
        });

        PaySlip_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PaySlip_Label.setText("Lastest payslip");

        LastPayCheck_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastPayCheck_TextFieldActionPerformed(evt);
            }
        });

        Browse2_Button.setText("Browse");
        Browse2_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse2_ButtonActionPerformed(evt);
            }
        });

        Licence_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Licence_Label.setText("License");

        Licenses_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Licenses_TextFieldActionPerformed(evt);
            }
        });

        Browse3_Button.setText("Browse");
        Browse3_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Browse3_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Attachements)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ID_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IDDoc_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(Browse1_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Licenses_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(PaySlip_Label)
                                            .addGap(18, 18, 18)
                                            .addComponent(LastPayCheck_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Licence_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Browse2_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Browse3_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Attachements)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDDoc_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_Label)
                    .addComponent(Browse1_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastPayCheck_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaySlip_Label)
                    .addComponent(Browse2_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Licenses_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Licence_Label)
                    .addComponent(Browse3_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(573, 79));

        Next_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Next_Label.setText("Next Of Kin");

        FirstName2_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FirstName2_Label.setText("First Name");

        CellNo2_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CellNo2_Label.setText("Cell No");

        Surname2_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Surname2_Label.setText("Surname");

        Relationship_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Relationship_Label.setText("Relationship");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Next_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName2_Label)
                            .addComponent(Surname2_Label)
                            .addComponent(CellNo2_Label))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cell2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Next_Surname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Next_FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Relationship_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Relationship_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Next_Label)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName2_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next_Surname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Surname2_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cell2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CellNo2_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Relationship_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Relationship_Label))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        Submit_Button.setText("Submit Application");
        Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Submit_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Submit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Gender_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gender_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Gender_ComboBoxActionPerformed

    private void Vehicle_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vehicle_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vehicle_ComboBoxActionPerformed

    private void LastPayCheck_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastPayCheck_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastPayCheck_TextFieldActionPerformed

    private void Licenses_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Licenses_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Licenses_TextFieldActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        Welcome F1 = new Welcome();
        F1.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Browse1_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse1_ButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File (System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            IDDoc_TextField.setText(selectedFile.getAbsolutePath().toString());
        }
    }//GEN-LAST:event_Browse1_ButtonActionPerformed

    private void Browse2_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse2_ButtonActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File (System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            LastPayCheck_TextField.setText(selectedFile.getAbsolutePath().toString());
        }
    }//GEN-LAST:event_Browse2_ButtonActionPerformed

    private void Browse3_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Browse3_ButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File (System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            Licenses_TextField.setText(selectedFile.getAbsolutePath().toString());
        }
    }//GEN-LAST:event_Browse3_ButtonActionPerformed

     
   
    private void Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_ButtonActionPerformed
        if (Yes_RadioButton.isSelected()) { 

            try { 

                PrintWriter myWriter = new PrintWriter(FirstName_TextField.getText() + " " + Surname_TextField.getText() + ".txt"); 

                myWriter.println("Personal Information."); 

                myWriter.println("---------------------------------------------------------------------"); 

                myWriter.println("Fullnames: " + FirstName_TextField.getText() + " " + Surname_TextField.getText()); 

                myWriter.println("ID Number: " + ID_TextField.getText()); 

                myWriter.println("Cell Number: " + Cell_TextField.getText()); 

                myWriter.println("Gender: " + Gender_ComboBox.toString()); 

                myWriter.println("Ocuupation: " + Occupation_TextField.getText()); 

                myWriter.println("Home Address: " + HomeAddress_TextField.getText()); 

                myWriter.println("Work Address: " + WorkAddress_TextField.getText()); 

                myWriter.println("Gross Pay: " + GrossPay_TextField.getText()); 

                myWriter.println("Net Pay: " + NetPay_TextField.getText()); 

                myWriter.println("Valid Licese: " + Licenses_TextField.toString()); 

                myWriter.println("Model: " + Vehicle_ComboBox.toString()); 
                //Next of kin
                
                myWriter.println("\nNext of kin Information."); 

                myWriter.println("---------------------------------------------------------------------"); 

                myWriter.println("Fullnames: " + Next_FirstName_TextField.getText() + " " + Next_Surname_TextField.getText()); 
                myWriter.println("ID Number: " + Cell2_TextField.getText()); 
                myWriter.println("ID Number: " + Relationship_TextField.getText()); 
                myWriter.close(); 
                JOptionPane.showMessageDialog(new Finance(), "Application sent."); 

             } catch (IOException e) { 
                System.out.println("An error occurred."); 
                e.printStackTrace(); 

            } 
           new Welcome().setVisible(true); 
           this.setVisible(false); 
           Yes_RadioButton.equals("Yes"); 
        } else { 

            JOptionPane.showMessageDialog(new Finance(), "You need a valid license to purchase a car."); 
            new Welcome().setVisible(true); 
            this.setVisible(false);
        }
    }//GEN-LAST:event_Submit_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Attachements;
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Browse1_Button;
    private javax.swing.JButton Browse2_Button;
    private javax.swing.JButton Browse3_Button;
    private javax.swing.JTextField Cell2_TextField;
    private javax.swing.JLabel CellNo2_Label;
    private javax.swing.JLabel CellNo_Label;
    private javax.swing.JTextField Cell_TextField;
    private javax.swing.JLabel FirstName2_Label;
    private javax.swing.JLabel FirstName_Label;
    private javax.swing.JTextField FirstName_TextField;
    private javax.swing.JComboBox<String> Gender_ComboBox;
    private javax.swing.JLabel Gender_Label;
    private javax.swing.JTextField GrossPay_TextField;
    private javax.swing.JLabel Gross_Label;
    private javax.swing.JLabel HomeAddress_Label;
    private javax.swing.JTextField HomeAddress_TextField;
    private javax.swing.JTextField IDDoc_TextField;
    private javax.swing.JLabel IDNo_Label;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JTextField LastPayCheck_TextField;
    private javax.swing.JLabel Licence_Label;
    private javax.swing.JTextField Licenses_TextField;
    private javax.swing.JTextField NetPay_TextField;
    private javax.swing.JLabel Net_Label;
    private javax.swing.JTextField Next_FirstName_TextField;
    private javax.swing.JLabel Next_Label;
    private javax.swing.JTextField Next_Surname_TextField;
    private javax.swing.JRadioButton No_RadioButton;
    private javax.swing.JLabel Occupation_Label;
    private javax.swing.JTextField Occupation_TextField;
    private javax.swing.JLabel PaySlip_Label;
    private javax.swing.JLabel Personal_Label;
    private javax.swing.JLabel Relationship_Label;
    private javax.swing.JTextField Relationship_TextField;
    private javax.swing.JButton Submit_Button;
    private javax.swing.JLabel Surname2_Label;
    private javax.swing.JLabel Surname_Label;
    private javax.swing.JTextField Surname_TextField;
    private javax.swing.JLabel VaildLicense_Label;
    private javax.swing.JComboBox<String> Vehicle_ComboBox;
    private javax.swing.JLabel Vehicle_Label;
    private javax.swing.JTextField WorkAddress_TextField;
    private javax.swing.JLabel WorkAdress_Label;
    private javax.swing.JRadioButton Yes_RadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
