/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dealership;

import javax.swing.ImageIcon;

/**
 *
 * @author nellt
 */
public class ViewCars extends javax.swing.JFrame {

    /**
     * Creates new form ViewCars
     */
    public ViewCars() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_Button = new javax.swing.JButton();
        Choose_Label = new javax.swing.JLabel();
        Cars_ComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        CarPic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        InstalmentNo_Label = new javax.swing.JLabel();
        SellingNo_Label = new javax.swing.JLabel();
        InterestNo_Label = new javax.swing.JLabel();
        DepositNo_Label = new javax.swing.JLabel();
        BallonNo_Label = new javax.swing.JLabel();
        InstalmentsNo_Label = new javax.swing.JLabel();
        TotalNo_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        Choose_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Choose_Label.setText("Please Choose your preferred car");

        Cars_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polo", "Polo Vivo", "T-Cross", "T-Roc" }));
        Cars_ComboBox.setSelectedIndex(-1);
        Cars_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cars_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CarPic, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CarPic, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Instalment");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Selling Price");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Interest Rate");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Deposit");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ballon Payment");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Instalments");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Total Cost of Credit");

        InstalmentNo_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SellingNo_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        InterestNo_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        DepositNo_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        BallonNo_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        InstalmentsNo_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TotalNo_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalNo_Label)
                    .addComponent(InstalmentsNo_Label)
                    .addComponent(BallonNo_Label)
                    .addComponent(DepositNo_Label)
                    .addComponent(InterestNo_Label)
                    .addComponent(SellingNo_Label)
                    .addComponent(InstalmentNo_Label))
                .addGap(201, 201, 201))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InstalmentNo_Label))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SellingNo_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InterestNo_Label))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DepositNo_Label))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BallonNo_Label))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(InstalmentsNo_Label))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TotalNo_Label))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Choose_Label)
                        .addGap(0, 720, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Cars_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Choose_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cars_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        Welcome F1 = new Welcome();
        F1.setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    
    
    
    private void Cars_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cars_ComboBoxActionPerformed
        
       if (Cars_ComboBox.getSelectedIndex() == 0){
           ImageIcon picture = new ImageIcon("C:/Users/nellt/Documents/NetBeansProjects/Dealership/src/DealershipImgs/comfortline.png");
           CarPic.setIcon(picture);
           
           InstalmentNo_Label.setText("R3166");
           SellingNo_Label.setText("R237400");
           InterestNo_Label.setText("5.5%");
           DepositNo_Label.setText("0%");
           BallonNo_Label.setText("R94 960");
           InstalmentsNo_Label.setText("72");
           TotalNo_Label.setText("R300276");
           
       } else if(Cars_ComboBox.getSelectedIndex()== 1){
           ImageIcon picture = new ImageIcon("C:/Users/nellt/Documents/NetBeansProjects/Dealership/src/DealershipImgs/poloTsi.png");
           CarPic.setIcon(picture);
           
           InstalmentNo_Label.setText("R3404");
           SellingNo_Label.setText("R224300");
           InterestNo_Label.setText("7.59%");
           DepositNo_Label.setText("0%");
           BallonNo_Label.setText("R118879");
           InstalmentsNo_Label.setText("48");
           TotalNo_Label.setText("R282249");
           
       } else if(Cars_ComboBox.getSelectedIndex() == 2){
           ImageIcon picture = new ImageIcon("C:/Users/nellt/Documents/NetBeansProjects/Dealership/src/DealershipImgs/tcross.png");
           CarPic.setIcon(picture);
           
           InstalmentNo_Label.setText("R4450");
           SellingNo_Label.setText("R352300");
           InterestNo_Label.setText("5.57.59%");
           DepositNo_Label.setText("10.58%");
           BallonNo_Label.setText("R183196");
           InstalmentsNo_Label.setText("48");
           TotalNo_Label.setText("R393796"); 
           
       }   else if(Cars_ComboBox.getSelectedIndex()== 3){
           
           ImageIcon picture = new ImageIcon("C:/Users/nellt/Documents/NetBeansProjects/Dealership/src/DealershipImgs/troc.png");
           CarPic.setIcon(picture);
           
           InstalmentNo_Label.setText("R5 590");
           SellingNo_Label.setText("R494 300");
           InterestNo_Label.setText("7.59%");
           DepositNo_Label.setText("10.49");
           BallonNo_Label.setText("R271865");
           InstalmentsNo_Label.setText("48");
           TotalNo_Label.setText("R 557465"); 
       }              
    }//GEN-LAST:event_Cars_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel BallonNo_Label;
    private javax.swing.JLabel CarPic;
    private javax.swing.JComboBox<String> Cars_ComboBox;
    private javax.swing.JLabel Choose_Label;
    private javax.swing.JLabel DepositNo_Label;
    private javax.swing.JLabel InstalmentNo_Label;
    private javax.swing.JLabel InstalmentsNo_Label;
    private javax.swing.JLabel InterestNo_Label;
    private javax.swing.JLabel SellingNo_Label;
    private javax.swing.JLabel TotalNo_Label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
